Connect private message block to function.
WordPress/wporg-developer pull request #168
Opened 2023-01-16 04:34 UTC by StevenDufresne

Related to #162 

This PR implement the private access message.

## Screenshot
| Desktop | Mobile |
| --- | --- |

## Testing
1. Visit [get_the_block_template_html](http://localhost:8888/reference/functions/get_the_block_template_html/)
2. Expect so see the message.

2023-01-16 21:47 UTC, renintw approved these changes
👍 I can see the layout is the same as the screenshots in the description.

This [import](https://github.com/WordPress/wporg-developer/blob/ad305f6ee90c16f3a2f5e8d1b1d233a73be932e1/source/wp-content/themes/wporg-developer-2023/src/code-private-access/index.js#L2) is no longer needed as the `style.scss` is removed.

2023-01-16 23:18 UTC, ryelle requested changes
The `import './style.scss';` in index.js is breaking the build step, but removing that builds fine.

I have the same comment as #167 though — there's a design for these alert-style notices too, and this PR does not match it.
<img width="804" alt="Screenshot 2023-01-16 at 6 15 11 PM" src="https://user-images.githubusercontent.com/541093/212778907-e9ef90ae-a1ed-4631-9528-8551d92d7c79.png">

2023-01-19 07:00 UTC, StevenDufresne commented
This was updated to use the [notice block](https://github.com/WordPress/wporg-mu-plugins/pull/322).

## Screenshot
<img width="714" alt="Screen Shot 2023-01-19 at 3 59 10 PM" src="https://user-images.githubusercontent.com/1657336/213376205-67a892ea-beed-4f98-af0f-6f0e967fb5e7.png">

2023-01-20 17:54 UTC, ryelle approved these changes
Looks good 👍🏻

2023-01-20 17:55 UTC, merged