Fix Code Reference: Missing parsed code styles
WordPress/wporg-developer pull request #415
Opened 2023-11-29 15:15 UTC by outdoor2kode

Fixes #322

Apply `syntax-red` to the parameter type.

## Screenshot

![image](https://github.com/WordPress/wporg-developer/assets/18050944/4c878bba-290e-4e53-abdf-6c310cedf75a)

2023-11-29 20:54 UTC, adamwoodnz requested changes
👍 works for Parameters.

Looks like we need to do it for Return though as well

![Screenshot 2023-11-30 at 9 52 40 AM](https://github.com/WordPress/wporg-developer/assets/1017872/b2856964-e716-4a79-a1ab-052ab765af36)

2023-11-30 14:52 UTC, renintw commented
Cleaned up the CSS a bit so that the 'type' under both parameter and return has the same color, font, and font size.

## Updated Screenshot
![image](https://github.com/WordPress/wporg-developer/assets/18050944/a073ce60-6cb2-4afd-91a1-b54c3aa12d03)

2023-11-30 19:52 UTC, adamwoodnz reviewed
Looks good, one comment

2023-11-30 19:52 UTC, adamwoodnz commented on source/wp-content/themes/wporg-developer-2023/src/code-return-value/style.scss
> +		color: var(--wp--preset--color--syntax-red);
Combine these? The rules are the same.
```suggestion
	.return-type,
	.type {
		font-family: var(--wp--preset--font-family--monospace);
		font-size: var(--wp--preset--font-size--small);
		color: var(--wp--preset--color--syntax-red);
```

2023-12-03 20:25 UTC, adamwoodnz approved these changes
LGTM 🚀

2023-12-04 07:13 UTC, merged