Fix redundant empty result set messages
WordPress/wporg-developer pull request #416
Opened 2023-11-29 17:41 UTC by renintw

Fixes #338 

This PR fixes redundant empty result set messages by returning earlier when `$results_count <= 0`.
`0 results found for “xxxxxxx”.` is removed.

## Screenshot
![image](https://github.com/WordPress/wporg-developer/assets/18050944/ba7cd373-403a-4f10-8381-0fafd9a49418)

2023-11-29 20:44 UTC, adamwoodnz commented on source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php
> +	if ( 0 <= $results_count ) {
I think this should be changed otherwise the count will not be shown for any count over 0
```suggestion
	if ( 0 = $results_count ) {
```

2023-11-29 20:48 UTC, adamwoodnz requested changes
Message is removed for all result counts at present, see suggestion inline 🙂

2023-11-30 13:58 UTC, outdoor2kode commented on source/wp-content/themes/wporg-developer-2023/src/search-results-context/index.php
> +	if ( 0 <= $results_count ) {
ah... it was `$results_count <= 0` in the first place, and then yoda standard came in..
Thanks.

2023-11-30 19:48 UTC, adamwoodnz approved these changes
LGTM :shipit:

2023-12-01 08:21 UTC, merged